### ISSUE TITLE
ClassNotFoundException: OpenHashMap$$anonfun$1

### ISSUE THREAD

**Issue by pcallahan-r7** [gorillalabs/sparkling#79]
Get this error while compiling 

with
```
[gorillalabs/sparkling "2.1.3"]
[org.apache.spark/spark-sql_2.12 "2.4.7"]
[org.apache.spark/spark-hive_2.12 "2.4.7"]
```

```
Caused by: java.lang.ClassNotFoundException: org.apache.spark.util.collection.OpenHashMap$$anonfun$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at sparkling.serialization$register_spark.<clinit>(serialization.clj:110)
```

**Comment by chrisbetz** [comment]
Hi @sanel, @pcallahan-r7,

luckily, @obohrer-otm created PR #80 , which might solve your problem. I'll take a look and create a new version.

Thanks for your patience!

**Comment by sanel** [comment]
Thanks @chrisbetz!

**Comment by sanel** [comment]
@chrisbetz I've noticed you released a new version with Spark 3.x, which means it fixes this ticket and implements https://github.com/gorillalabs/sparkling/issues/78?

**Comment by chrisbetz** [comment]
@sanel Thanks for pointing this out. :)
